language: en
pipeline: supervised_embeddings
policies:
- btach_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- name: MemoizationPolicy
- name: FallbackPolicy
- name: MappingPolicy
